# Generated by Django 5.0.7 on 2025-07-19 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ai_matches',
            field=models.JSONField(blank=True, default=list, help_text='AI-generated tutor matches'),
        ),
        migrations.AddField(
            model_name='order',
            name='ai_matches_processed',
            field=models.BooleanField(default=False, help_text='Whether AI matching has been processed'),
        ),
    ]
