[build]
  base = ""
  publish = "staticfiles/"
  command = "python manage.py collectstatic --noinput"

[build.environment]
  DJANGO_SETTINGS_MODULE = "tutors_platform.settings.production"
  PYTHON_VERSION = "3.11"

[context.production.environment]
  DJANGO_SETTINGS_MODULE = "tutors_platform.settings.production"

[context.develop.environment]  
  DJANGO_SETTINGS_MODULE = "tutors_platform.settings.development"

# Redirects for SPA behavior (если есть фронтенд)
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"