# Generated by Django 5.0.7

import pgvector.django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorprofile',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='premium_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tutorprofile',
            name='stripe_customer_id',
            field=models.CharField(blank=True, help_text='Stripe customer ID for subscription management', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tutorprofile',
            name='vector',
            field=pgvector.django.VectorField(blank=True, dimensions=1536, null=True),
        ),
    ]